version: "3"
services:
  service:
    depends_on:
      - mysql
    links:
      - mysql
    image: service
    build:
      dockerfile: service/Dockerfile
    ports:
      - 9300:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lpms
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: lpms