version: "3"
services:

  service:
    depends_on:
      - mysql
    links:
      - mysql
    image: service
    build:
      dockerfile: service/Dockerfile
    ports:
      - 9300:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lpms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&max_allowed_packet=15728640
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: lpms

  server:
    depends_on:
      - mysql
      - service
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 1337:80